server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/news
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  redis:
    host: 127.0.01
    port: 6379
    password: root
    database: 1
    lettuce:
      pool:
        max-active: 10
        max-idle: 1
        min-idle: 0
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.bdqn.springbootdemo.bean
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


token:
  timeout: 10
